modules:
  gatling:
    version: 3.2.1

execution:
- executor: gatling
  scenario: Municipality-AnonymousInvalid
  concurrency: 1
  iterations: 1
  hold-for: 20m
  ramp-up: 10s
  locations:
    eu-west-1: 2

scenarios:
  Municipality-AnonymousInvalid:
    script: MunicipalitySimulation.scala
    simulation: registry.municipality.AnonymousInvalidTrafficLoadForMunicipality
    properties:
      api_key: REPLACE_ME
      base_url: https://api.basisregisters.vlaanderen.be/v1
      warmup_url: https://api.basisregisters.vlaanderen.be/v1/versions
