modules:
  gatling:
    version: 3.2.1

execution:
- executor: gatling
  scenario: Parcel-Peak
  concurrency: 1
  iterations: 1
  hold-for: 1h
  ramp-up: 30m
  locations:
    eu-west-1: 2

scenarios:
  Parcel-Peak:
    script: ParcelSimulation.scala
    simulation: registry.parcel.PeakTrafficLoadForParcel
    properties:
      api_key: xxx
      base_url: https://api.basisregisters.vlaanderen.be/v1
      warmup_url: https://api.basisregisters.vlaanderen.be/v1/versions
