name: Run K6 test
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Environment to run the test'
        required: true
        default: staging
        options:
        - staging
        - production

jobs:
  run-test:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    services:
      dd-agent:
        image: gcr.io/datadoghq/agent:latest
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_HOSTNAME: "none"
          DD_SITE: "datadoghq.com"
          DD_DOGSTATSD_NON_LOCAL_TRAFFIC: true
        ports:
          - 8125:8125/udp

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/setup-k6-action@v1
        with:
          k6-version: '0.54.0'

      - name: Run local k6 test
        uses: grafana/run-k6-action@v1
        with:
          path: src/main.js
        env:
          K6_OUT: statsd
          K6_STATSD_ENABLE_TAGS: true
          BASE_URL: ${{ vars.BASE_URL }}
          API_KEY: ${{ secrets.API_KEY }}
          DD_ENV: vbr-${{ inputs.environment }}
          DD_TAGS: env:vbr-${{ inputs.environment }}